import Head from 'next/head';
import { css } from '@emotion/react';
import { useState } from 'react';
import Image from 'next/image';

const formStyles = css`
  display: flex;
  align-items: center;
  gap: 12px;
  border: 2px solid black;
`;
const selectStyles = css`
  width: 100px;
  font-size: 16px;
  padding: 4px;
`;
const inputSubmitStyles = css`
  font-size: 16px;
  padding: 4px;
  cursor: pointer;
`;

type CreateRecipeResponseBody = {
  recipe: {
    id: number;
    effort: string;
    imageurl: string;
    name: string;
    taste: string;
    type: string;
  };
};
export default function Home() {
  const [foodType, setFoodType] = useState('');
  const [foodTaste, setFoodTaste] = useState('');
  const [foodEffort, setFoodEffort] = useState('');
  const [recipeBoolean, setRecipeBoolean] = useState(false);
  const [randomRecipeImage, setRandomRecipeImage] = useState('');
  const [randomRecipeName, setRandomRecipeName] = useState('');

  function handleSelectFoodType(event: React.ChangeEvent<HTMLSelectElement>) {
    const type = event.target.value;
    setFoodType(type);
  }
  function handleSelectFoodTaste(event: React.ChangeEvent<HTMLSelectElement>) {
    const taste = event.target.value;
    setFoodTaste(taste);
  }
  function handleSelectFoodEffort(event: React.ChangeEvent<HTMLSelectElement>) {
    const effort = event.target.value;
    setFoodEffort(effort);
  }

  return (
    <div>
      <Head>
        <title>Random Recipe Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Willkommen zu Omas zufälligem Rezeptgenerator</h1>
        <form
          css={formStyles}
          onSubmit={async (e) => {
            e.preventDefault();

            const createPersonResponse = await fetch('/api/recipe', {
              method: 'POST',
              headers: {
                'Content-Type': 'application/json',
              },
              body: JSON.stringify({
                type: foodType,
                taste: foodTaste,
                effort: foodEffort,
              }),
            });

            const createRecipeResponseBody =
              (await createPersonResponse.json()) as CreateRecipeResponseBody;
            console.log(createRecipeResponseBody);
            if ('recipe' in createRecipeResponseBody) {
              setRecipeBoolean(true);
              setRandomRecipeImage(createRecipeResponseBody.recipe.imageurl);
              setRandomRecipeName(createRecipeResponseBody.recipe.name);

              //   setEventList(createdEvents);
              //   setEventName('');
            }

            // if ('errors' in createRecipeResponseBody) {
            //   setErrors(createRecipeResponseBody.errors);
            //   return;
            // }
          }}
        >
          <div>
            <h4>Speisenart</h4>
            <select css={selectStyles} onChange={handleSelectFoodType}>
              <option value="default">Optionen</option>
              <option value="starter">Vorspeise</option>
              <option value="main">Hauptspeise</option>
              <option value="dessert">Nachspeise</option>
            </select>
          </div>
          <div>
            <h4>Salzig oder Süß</h4>
            <select css={selectStyles} onChange={handleSelectFoodTaste}>
              <option value="default">Optionen</option>
              <option value="salt">Salzig</option>
              <option value="sweet">Süß</option>
            </select>
          </div>
          <div>
            <h4>Aufwand</h4>
            <select css={selectStyles} onChange={handleSelectFoodEffort}>
              <option value="default">Optionen</option>
              <option value="low">Gering</option>
              <option value="middle">Mittel</option>
              <option value="high">Hoch</option>
            </select>
          </div>

          <input
            css={inputSubmitStyles}
            type="submit"
            value="Suche ein Rezept"
          />
        </form>
        {recipeBoolean && (
          <div>
            <h2>{randomRecipeName}</h2>
            <Image
              src={randomRecipeImage}
              height="350px"
              width="480px"
              alt="Image of the random recipe"
            />
          </div>
        )}
      </main>
    </div>
  );
}
